### ISSUE TITLE
Fix UIImage force unwraps

### ISSUE THREAD

**Issue by chriscombs** [nodes-ios/Codemine#30]
UIImage+Utilities.swift has a lot of force unwraps due to the swift 2.3 changes. I didn't have time to restructure things in a more safe way.

**Comment by dominik-hadl** [comment]
Why not just make the method signatures return nil and then do guards? That takes 1 minute. Also noticed there are some semicolons at the ends of some lines.

**Comment by chriscombs** [comment]
Turns out this was also an issue in the swift-3.0 branch, fixed it there as well.
