### ISSUE TITLE
100% code coverage 😄

### ISSUE THREAD

**Issue by chriscombs** [nodes-ios/Codemine#32]

**Comment by dominik-hadl** [comment]
👍 💯

**Comment by mariusc** [comment]
We're at 95%. Not sure how to test Application and UIView extensions

**Comment by mariusc** [comment]
95% is good enough for a syntactic sugar framework. Application is almost impossible to test anyway. Having better code coverage is nice, but there's no need to have an issue for this anymore. Closing.
