### ISSUE TITLE
UIView rounded corners tweaks

### ISSUE THREAD

**Issue by mariusc** [nodes-ios/Codemine#40]
We have the `roundViewCorners` method. I'm not sure if anyone ever used it, and I'm not 100% sure it works as expected. We don't have tests for it either. We should check that it does what it should.

iOS 11 introduces `CACornerMask`, so on the swift 4 branch, we no longer need to create the path manually and mask it, we can instead do something like `view.layer.maskedCorners = [.layerMaxXMaxYCorner, .layerMinXMaxYCorner]` inside of an `#available` check, and keep the previous code for older iOS versions.

This is the method I'm talking about https://github.com/nodes-ios/Codemine/blob/master/Codemine/Extensions/UIView%2BUtilities.swift#L32

**Comment by chriscombs** [comment]
I just used it in Spenn yesterday and it didn't work quite right

**Comment by endodoug** [comment]
I'd like to work on this one later tonight.

**Comment by endodoug** [comment]
Sorry, I couldn't get to it tonight.  If it's not completed tomorrow I'll have some time.  Don't wait on me if someone else can get to it.

**Comment by mariusc** [comment]
Done in #46
