### ISSUE TITLE
Update regex for email validation, so the tests pass

### ISSUE THREAD

**Issue by mariusc** [nodes-ios/Codemine#7]
The regex used is: `[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}`

Some tests fail:

> .email@example.com was considered valid, but it is not
> email.@example.com was considered valid, but it is not
> email..email@example.com was considered valid, but it is not
> email@-example.com was considered valid, but it is not
> email@example..com was considered valid, but it is not
> Abc..123@example.com was considered valid, but it is not

**Comment by mariusc** [comment]
Fixed in ca52b0035878b759c21551a8a5503456ec58e102

**Comment by dominik-hadl** [comment]
@mariusc You shouldn't merge your own pull requests when changing functionality like this. Merging a typo fix pull request is ofc fine, but this might affect performance, functionality and our existing apps.

The new expression looks and works ok (in a few of my tests), but is 3 - 4 times slower than the previous one. Let's leave it there for now, as it probably won't be an issue, but just for the future reference, keep the PR opened for some time and assign someone to it :)

**Comment by mariusc** [comment]
@nickskull Got it :+1:
