### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by dominik-hadl** [nodes-ios/Codemine#9]
For build & test automation.

**Comment by dominik-hadl** [comment]
[This file](https://github.com/nodes-ios/KeyboardHelper/blob/master/.travis.yml) can be used as a reference, it just needs some small tweaks to make it work with this repo. I've already enabled this repo in Travis, so once the config file is added everything should run.

**Comment by mariusc** [comment]
Fixed in 664a75c7ce03c0109f43c974395c6b3be1305c2f
